# Generated by Django 4.1.3 on 2023-02-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('address', models.TextField()),
                ('phone_number', models.SmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
