# Generated by Django 4.1.3 on 2023-02-28 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('address', models.TextField()),
                ('phone_number', models.SmallIntegerField()),
                ('salary', models.TextField()),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello.job')),
            ],
        ),
    ]
