# Generated by Django 4.1.3 on 2023-02-28 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('expriration_date', models.TextField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello.employees')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello.type')),
            ],
        ),
    ]
