# Generated by Django 4.1.3 on 2023-02-28 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_furniture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.TextField()),
                ('quantity', models.TextField()),
                ('total_amount', models.TextField()),
                ('number_of_doc', models.TextField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello.customers')),
                ('emplouee_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello.employees')),
                ('furniture_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello.furniture')),
            ],
        ),
    ]
